using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace VFridge.Api.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""users"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""username"" character varying(50) NOT NULL,
                    ""email"" character varying(100) NOT NULL,
                    ""password"" text NOT NULL,
                    ""created_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
                    ""preferred_language"" character varying(8) NOT NULL DEFAULT 'en',
                    ""cuisine_preference"" character varying(32) NOT NULL DEFAULT 'any',
                    ""dietary_profile"" character varying(1000),
                    ""avatar"" character varying(50),
                    ""daily_calories_target"" integer,
                    ""daily_protein_target"" numeric(6,2),
                    ""daily_fat_target"" numeric(6,2),
                    ""daily_carbs_target"" numeric(6,2)
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""users_email_key"" ON ""users"" (""email"");

                CREATE TABLE IF NOT EXISTS ""fridges"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""name"" character varying(80) NOT NULL,
                    ""owner_id"" integer NOT NULL REFERENCES ""users""(""id"") ON DELETE CASCADE,
                    ""created_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP)
                );
                CREATE INDEX IF NOT EXISTS ""ix_fridges_owner"" ON ""fridges"" (""owner_id"");

                CREATE TABLE IF NOT EXISTS ""products"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""name"" character varying(255) NOT NULL,
                    ""quantity"" numeric(10,2),
                    ""unit"" character varying(20),
                    ""expiry_date"" date,
                    ""description"" text,
                    ""created_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
                    ""owner_id"" integer NOT NULL REFERENCES ""users""(""id"") ON DELETE CASCADE,
                    ""category"" character varying(32) NOT NULL DEFAULT 'other',
                    ""fridge_id"" integer NOT NULL REFERENCES ""fridges""(""id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""ix_products_fridge"" ON ""products"" (""fridge_id"");

                CREATE TABLE IF NOT EXISTS ""chat"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""user_id"" integer NOT NULL REFERENCES ""users""(""id"") ON DELETE CASCADE,
                    ""role"" character varying(20) NOT NULL,
                    ""content"" text NOT NULL,
                    ""created_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP)
                );

                CREATE TABLE IF NOT EXISTS ""consumption_log"" (
                    ""id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""user_id"" integer NOT NULL,
                    ""fridge_id"" integer NOT NULL,
                    ""product_name"" character varying(255) NOT NULL,
                    ""quantity"" numeric(10,2),
                    ""unit"" character varying(20),
                    ""category"" character varying(32) NOT NULL DEFAULT 'other',
                    ""status"" character varying(16) NOT NULL,
                    ""age_days"" integer,
                    ""consumed_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP)
                );
                CREATE INDEX IF NOT EXISTS ""ix_consumption_log_user_consumed_at"" ON ""consumption_log"" (""user_id"", ""consumed_at"");
                CREATE INDEX IF NOT EXISTS ""ix_consumption_log_user_status"" ON ""consumption_log"" (""user_id"", ""status"");
                CREATE INDEX IF NOT EXISTS ""ix_consumption_log_fridge"" ON ""consumption_log"" (""fridge_id"");

                CREATE TABLE IF NOT EXISTS ""email_verifications"" (
                    ""user_id"" integer PRIMARY KEY REFERENCES ""users""(""id"") ON DELETE CASCADE,
                    ""verified_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP)
                );

                CREATE TABLE IF NOT EXISTS ""email_verification_tokens"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""user_id"" integer NOT NULL REFERENCES ""users""(""id"") ON DELETE CASCADE,
                    ""token_hash"" text NOT NULL,
                    ""expires_at"" timestamp without time zone NOT NULL,
                    ""used_at"" timestamp without time zone,
                    ""created_at"" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                );
                CREATE INDEX IF NOT EXISTS ""ix_email_verification_tokens_hash"" ON ""email_verification_tokens"" (""token_hash"");
                CREATE INDEX IF NOT EXISTS ""ix_email_verification_tokens_user"" ON ""email_verification_tokens"" (""user_id"");

                CREATE TABLE IF NOT EXISTS ""fridge_invites"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""fridge_id"" integer NOT NULL REFERENCES ""fridges""(""id"") ON DELETE CASCADE,
                    ""email"" character varying(255) NOT NULL,
                    ""token_hash"" text NOT NULL,
                    ""expires_at"" timestamp without time zone NOT NULL,
                    ""accepted_at"" timestamp without time zone,
                    ""created_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP)
                );
                CREATE INDEX IF NOT EXISTS ""ix_fridge_invites_fridge"" ON ""fridge_invites"" (""fridge_id"");
                CREATE INDEX IF NOT EXISTS ""ix_fridge_invites_hash"" ON ""fridge_invites"" (""token_hash"");

                CREATE TABLE IF NOT EXISTS ""fridge_members"" (
                    ""fridge_id"" integer NOT NULL REFERENCES ""fridges""(""id"") ON DELETE CASCADE,
                    ""user_id"" integer NOT NULL REFERENCES ""users""(""id"") ON DELETE CASCADE,
                    ""role"" character varying(16) NOT NULL,
                    ""joined_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
                    PRIMARY KEY (""fridge_id"", ""user_id"")
                );
                CREATE INDEX IF NOT EXISTS ""ix_fridge_members_user"" ON ""fridge_members"" (""user_id"");

                CREATE TABLE IF NOT EXISTS ""meal_plans"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""fridge_id"" integer NOT NULL REFERENCES ""fridges""(""id"") ON DELETE CASCADE,
                    ""meals_json"" text NOT NULL,
                    ""gap_items_json"" text NOT NULL,
                    ""created_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
                    ""updated_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP)
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_meal_plans_fridge_id"" ON ""meal_plans"" (""fridge_id"");

                CREATE TABLE IF NOT EXISTS ""nutrition_logs"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""user_id"" integer NOT NULL REFERENCES ""users""(""id"") ON DELETE CASCADE,
                    ""date"" date NOT NULL,
                    ""meal_type"" character varying(32) NOT NULL,
                    ""food_name"" character varying(255) NOT NULL,
                    ""quantity"" numeric(10,2) NOT NULL,
                    ""unit"" character varying(20) NOT NULL,
                    ""calories"" integer NOT NULL,
                    ""protein"" numeric(6,2) NOT NULL,
                    ""fat"" numeric(6,2) NOT NULL,
                    ""carbs"" numeric(6,2) NOT NULL,
                    ""logged_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP)
                );
                CREATE INDEX IF NOT EXISTS ""ix_nutrition_logs_user_date"" ON ""nutrition_logs"" (""user_id"", ""date"");

                CREATE TABLE IF NOT EXISTS ""oauth_logins"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""user_id"" integer NOT NULL REFERENCES ""users""(""id"") ON DELETE CASCADE,
                    ""provider"" character varying(20) NOT NULL,
                    ""provider_user_id"" character varying(255) NOT NULL,
                    ""created_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP)
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_oauth_logins_provider_provider_user_id"" ON ""oauth_logins"" (""provider"", ""provider_user_id"");
                CREATE INDEX IF NOT EXISTS ""ix_oauth_logins_user"" ON ""oauth_logins"" (""user_id"");

                CREATE TABLE IF NOT EXISTS ""refresh_tokens"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""user_id"" integer NOT NULL REFERENCES ""users""(""id"") ON DELETE CASCADE,
                    ""token_hash"" text NOT NULL,
                    ""expires_at"" timestamp without time zone NOT NULL,
                    ""revoked_at"" timestamp without time zone,
                    ""created_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP)
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_refresh_tokens_token_hash"" ON ""refresh_tokens"" (""token_hash"");
                CREATE INDEX IF NOT EXISTS ""ix_refresh_tokens_user"" ON ""refresh_tokens"" (""user_id"");

                CREATE TABLE IF NOT EXISTS ""saved_recipes"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""user_id"" integer NOT NULL REFERENCES ""users""(""id"") ON DELETE CASCADE,
                    ""fridge_id"" integer NOT NULL,
                    ""name"" character varying(255) NOT NULL,
                    ""description"" text,
                    ""ingredients_json"" text NOT NULL,
                    ""steps_json"" text NOT NULL,
                    ""calories"" integer,
                    ""protein"" numeric(6,2),
                    ""fat"" numeric(6,2),
                    ""carbs"" numeric(6,2),
                    ""created_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP)
                );
                CREATE INDEX IF NOT EXISTS ""ix_saved_recipes_user_id"" ON ""saved_recipes"" (""user_id"");

                CREATE TABLE IF NOT EXISTS ""shopping_items"" (
                    ""id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""user_id"" integer NOT NULL REFERENCES ""users""(""id"") ON DELETE CASCADE,
                    ""name"" character varying(255) NOT NULL,
                    ""quantity"" numeric(10,2),
                    ""unit"" character varying(20),
                    ""category"" character varying(32) NOT NULL DEFAULT 'other',
                    ""checked"" boolean NOT NULL,
                    ""created_at"" timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
                    ""fridge_id"" integer NOT NULL
                );
                CREATE INDEX IF NOT EXISTS ""ix_shopping_items_fridge"" ON ""shopping_items"" (""fridge_id"");
                CREATE INDEX IF NOT EXISTS ""ix_shopping_items_user"" ON ""shopping_items"" (""user_id"");
                CREATE INDEX IF NOT EXISTS ""ix_shopping_items_user_checked"" ON ""shopping_items"" (""user_id"", ""checked"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "chat");

            migrationBuilder.DropTable(
                name: "consumption_log");

            migrationBuilder.DropTable(
                name: "email_verification_tokens");

            migrationBuilder.DropTable(
                name: "email_verifications");

            migrationBuilder.DropTable(
                name: "fridge_invites");

            migrationBuilder.DropTable(
                name: "fridge_members");

            migrationBuilder.DropTable(
                name: "meal_plans");

            migrationBuilder.DropTable(
                name: "nutrition_logs");

            migrationBuilder.DropTable(
                name: "oauth_logins");

            migrationBuilder.DropTable(
                name: "products");

            migrationBuilder.DropTable(
                name: "refresh_tokens");

            migrationBuilder.DropTable(
                name: "saved_recipes");

            migrationBuilder.DropTable(
                name: "shopping_items");

            migrationBuilder.DropTable(
                name: "fridges");

            migrationBuilder.DropTable(
                name: "users");
        }
    }
}
